# Generated by Django 5.0.6 on 2024-07-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='username',
            new_name='username1',
        ),
    ]
