# Generated by Django 5.0.6 on 2024-07-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0005_services_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_pics',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
