# Generated by Django 5.0.6 on 2024-07-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0007_home_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_source',
            name='Top_Header_video',
        ),
        migrations.RemoveField(
            model_name='home_source',
            name='image',
        ),
        migrations.AddField(
            model_name='home_source',
            name='status',
            field=models.BooleanField(default=False, help_text='0-show,1=Hidden'),
        ),
    ]
