# Generated by Django 5.0.6 on 2024-07-09 07:22

import ZebraApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0009_home_source_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_source',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home_source',
            name='logo',
            field=models.ImageField(null=True, upload_to=ZebraApp.models.getFileName),
        ),
        migrations.AddField(
            model_name='home_source',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
