# Generated by Django 5.0.6 on 2024-07-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0010_home_source_description_home_source_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_source',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
