# Generated by Django 5.0.6 on 2024-07-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0011_alter_home_source_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_source',
            name='logo_name',
            field=models.CharField(default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='home_source',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
