# Generated by Django 5.0.6 on 2024-07-09 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0012_home_source_logo_name_alter_home_source_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_sourceAdmin',
            fields=[
                ('home_source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ZebraApp.home_source')),
            ],
            bases=('ZebraApp.home_source',),
        ),
        migrations.AlterModelTable(
            name='home_source',
            table='Home_source',
        ),
    ]
