# Generated by Django 5.0.6 on 2024-07-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0013_home_sourceadmin_alter_home_source_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='home_source',
            table='HOME_SOURCE',
        ),
        migrations.DeleteModel(
            name='Home_sourceAdmin',
        ),
    ]
