# Generated by Django 5.0.6 on 2024-07-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0014_alter_home_source_table_delete_home_sourceadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_source',
            name='utube_link',
            field=models.URLField(blank=True, help_text='Enter the URL of the website', verbose_name='Website URL'),
        ),
    ]
