# Generated by Django 5.0.6 on 2024-07-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0017_home_url_home_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_url',
            name='Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
