# Generated by Django 5.0.6 on 2024-07-10 08:58

import ZebraApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0018_home_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_source',
            name='Project_Block_Vdo_2',
            field=models.FileField(blank=True, null=True, upload_to=ZebraApp.models.getFileName),
        ),
        migrations.AddField(
            model_name='home_source',
            name='Project_Block_img_1',
            field=models.ImageField(blank=True, null=True, upload_to=ZebraApp.models.getFileName),
        ),
        migrations.AlterField(
            model_name='home_source',
            name='Title',
            field=models.CharField(max_length=50, verbose_name='Title for this data'),
        ),
        migrations.AlterField(
            model_name='home_source',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='Describtion will show under subject'),
        ),
        migrations.AlterField(
            model_name='home_source',
            name='logo',
            field=models.ImageField(null=True, upload_to=ZebraApp.models.getFileName, verbose_name='add a logo for counter'),
        ),
        migrations.AlterField(
            model_name='home_source',
            name='logo_name',
            field=models.CharField(default=False, max_length=20, null=True, verbose_name='logo name'),
        ),
        migrations.AlterField(
            model_name='home_source',
            name='subject',
            field=models.CharField(max_length=50, null=True, verbose_name='Subject will show under the logo'),
        ),
        migrations.AlterField(
            model_name='home_source',
            name='video',
            field=models.FileField(null=True, upload_to=ZebraApp.models.getFileName, verbose_name='Upload a video to show in Slider'),
        ),
    ]
