# Generated by Django 5.0.6 on 2024-07-10 09:32

import ZebraApp.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0019_home_source_project_block_vdo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_source',
            name='Project_Block_Vdo_2',
            field=models.FileField(default=django.utils.timezone.now, upload_to=ZebraApp.models.getFileName),
            preserve_default=False,
        ),
    ]
