# Generated by Django 5.0.6 on 2024-07-11 04:49

import ZebraApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0020_alter_home_source_project_block_vdo_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.ImageField(upload_to=ZebraApp.models.getFileName)),
            ],
        ),
    ]
