# Generated by Django 5.0.6 on 2024-07-11 04:54

import ZebraApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0021_service_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_page',
            name='Header',
            field=models.FileField(upload_to=ZebraApp.models.getFileName),
        ),
    ]
