# Generated by Django 5.0.6 on 2024-07-11 05:07

import ZebraApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0022_alter_service_page_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_page',
            name='Header',
            field=models.FileField(null=True, upload_to=ZebraApp.models.getFileName),
        ),
    ]
