# Generated by Django 5.0.6 on 2024-07-11 07:08

import ZebraApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0023_alter_service_page_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Header', models.FileField(blank=True, null=True, upload_to=ZebraApp.models.getFileName)),
            ],
        ),
    ]
