# Generated by Django 5.0.6 on 2024-07-11 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0024_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projects',
            new_name='projects_model',
        ),
    ]
