# Generated by Django 5.0.6 on 2024-07-12 07:05

import ZebraApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0025_rename_projects_projects_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_album_name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ZebraApp.models.getFileName)),
                ('Customer', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(max_length=500)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projects_model',
            name='Project_Header',
            field=models.FileField(null=True, upload_to=ZebraApp.models.getFileName),
        ),
        migrations.CreateModel(
            name='Project_site_pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to=ZebraApp.models.getFileName)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZebraApp.project_catagory')),
            ],
        ),
    ]
