# Generated by Django 5.0.6 on 2024-07-12 12:00

import ZebraApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0026_project_catagory_alter_projects_model_project_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_site_pics',
            name='project_image',
            field=models.ImageField(null=True, upload_to=ZebraApp.models.getFileName),
        ),
    ]
