# Generated by Django 5.0.6 on 2024-07-15 06:46

import ZebraApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0028_about_us_alter_home_source_project_block_vdo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_source',
            name='Title',
            field=models.CharField(max_length=50, null=True, verbose_name='Title for this data'),
        ),
        migrations.AlterField(
            model_name='home_source',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Describtion will show under subject'),
        ),
        migrations.AlterField(
            model_name='home_source',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=ZebraApp.models.getFileName, verbose_name='add a logo for counter'),
        ),
        migrations.AlterField(
            model_name='home_source',
            name='logo_name',
            field=models.CharField(blank=True, default=False, max_length=20, null=True, verbose_name='logo name'),
        ),
    ]
