# Generated by Django 5.0.6 on 2024-07-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0029_alter_home_source_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_logo_name', models.CharField(blank=True, max_length=20, null=True)),
                ('client_logos', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
