# Generated by Django 5.0.6 on 2024-07-15 07:28

import ZebraApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0030_client_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_logo',
            name='client_logos',
            field=models.ImageField(blank=True, null=True, upload_to=ZebraApp.models.getFileName),
        ),
    ]
