# Generated by Django 5.0.6 on 2024-07-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0031_alter_client_logo_client_logos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_logo',
            name='Client_logo_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
