# Generated by Django 5.0.6 on 2024-07-22 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0034_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_site_pics',
            name='catagory',
        ),
    ]
