# Generated by Django 5.0.6 on 2024-07-23 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0035_remove_project_site_pics_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_site_pics',
            name='catagory',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='ZebraApp.project_catagory'),
        ),
    ]

