# Generated by Django 5.0.6 on 2024-07-23 07:50

import ZebraApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0036_project_site_pics_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_catagory',
            name='Customer',
            field=models.CharField(blank=True, default=1, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project_catagory',
            name='Project_album_name',
            field=models.CharField(blank=1, default=1, max_length=150, null=1),
        ),
        migrations.AlterField(
            model_name='project_catagory',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project_site_pics',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project_site_pics',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to=ZebraApp.models.getFileName),
        ),
    ]
