# Generated by Django 5.0.6 on 2024-07-23 09:07

import ZebraApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZebraApp', '0037_alter_project_catagory_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_site_pics',
            old_name='project_image',
            new_name='project_image1',
        ),
        migrations.AddField(
            model_name='project_site_pics',
            name='project_image2',
            field=models.ImageField(blank=True, null=True, upload_to=ZebraApp.models.getFileName),
        ),
        migrations.AddField(
            model_name='project_site_pics',
            name='project_image3',
            field=models.ImageField(blank=True, null=True, upload_to=ZebraApp.models.getFileName),
        ),
    ]
